### PR TITLE
fix: well this was a stupid fix tbh

### PR DESCRIPTION
**Pull request by toni-schmitt**
this took me too long, i am embarssed

### CODE REVIEW

**Comment by toni-schmitt** [comment]
pls test if this works on your machine @kyomawolf

**Comment by kyomawolf** [comment]
Nope, doesnt work. 
Log output:
```[dumb-init] /usr/local/bin/start.sh: No such file or directory
[dumb-init] /usr/local/bin/start.sh: No such file or directory
[dumb-init] /usr/local/bin/start.sh: No such file or directory
[dumb-init] /usr/local/bin/start.sh: No such file or directory
[dumb-init] /usr/local/bin/start.sh: No such file or directory
[dumb-init] /usr/local/bin/start.sh: No such file or directory
[dumb-init] /usr/local/bin/start.sh: No such file or directory

**Comment by toni-schmitt** [comment]
well that was the only thing that worked on my machine, that sucks :/

**Comment by toni-schmitt** [comment]
@kyomawolf well, i just removed start.sh, don't know why this is the way it is, spent way too much time trying to figure it out :/

**Review by kyomawolf — APPROVED** [review]
Well done! more compact, less bloat and works smooth

**Pull request merged**
